"use client";

import Link from "next/link";
import { Panel, PageHeader, Badge, SectionLabel, Stat, Button, EmptyState } from "@/components/Panel";
import { MetricBadge, MetricHeuristicsNote, TERM_DEFINITIONS } from "@/components/MetricBadge";
import { ResearchJourney } from "@/components/ResearchJourney";
import { useActiveResearch, hasExperiment } from "@/lib/research-context";

function safeAvg(values: (number | null | undefined)[]): number | null {
  const clean = values.filter((v): v is number => v != null && v === v);
  if (!clean.length) return null;
  return clean.reduce((a, b) => a + b, 0) / clean.length;
}

export default function ExecutionPage() {
  const active = useActiveResearch();

  if (!active) {
    return <div className="stack">
      <ResearchJourney current="execution"/>
      <PageHeader kicker="Research / Market impact" title="Execution" description="A clear view of the assumptions sitting between a model signal and reported P&L." />
      <Panel><EmptyState title="No research experiment selected" description="Run Research first to generate execution/cost-sensitivity evidence." action={<Link href="/research"><Button>Go to Research Lab →</Button></Link>} /></Panel>
    </div>;
  }

  if (!hasExperiment(active)) {
    const hasDataset = !!active.dataset && active.dataset.dataset_id !== 'demo';
    return <div className="stack">
      <ResearchJourney current="execution"/>
      <PageHeader kicker="Research / Market impact" title="Execution" description="A clear view of the assumptions sitting between a model signal and reported P&L." />
      <Panel>
        {hasDataset ? (
          <EmptyState title={`${active.instrument} · ${active.timeframe} selected — no experiment yet`} description="Cost-sensitivity evidence is generated by a research run. Run Research on this dataset first." action={<Link href={`/research?dataset_id=${active.dataset!.dataset_id}`}><Button>Run Research on this dataset →</Button></Link>} />
        ) : (
          <EmptyState title="No research experiment selected" description="Run Research first to generate execution/cost-sensitivity evidence." action={<Link href="/research"><Button>Go to Research Lab →</Button></Link>} />
        )}
      </Panel>
    </div>;
  }

  const folds: any[] = active.full_result?.metrics?.folds ?? [];
  const costRows: any[] = folds.flatMap((f: any) => f.cost_sensitivity ?? []);
  const hasCostDetail = costRows.length > 0;
  const cfg = active.execution_config;

  // Average net/gross Sharpe and cost drag at each cost multiplier, across folds.
  const byMultiplier = new Map<number, { gross_sharpe: number[]; net_sharpe: number[]; total_cost_drag: number[] }>();
  for (const row of costRows) {
    const m = row.cost_multiplier;
    const bucket = byMultiplier.get(m) ?? { gross_sharpe: [], net_sharpe: [], total_cost_drag: [] };
    if (row.gross_sharpe === row.gross_sharpe) bucket.gross_sharpe.push(row.gross_sharpe);
    if (row.net_sharpe === row.net_sharpe) bucket.net_sharpe.push(row.net_sharpe);
    if (row.total_cost_drag === row.total_cost_drag) bucket.total_cost_drag.push(row.total_cost_drag);
    byMultiplier.set(m, bucket);
  }
  const multipliers = Array.from(byMultiplier.keys()).sort((a, b) => a - b);

  return <div className="stack">
    <ResearchJourney current="execution"/>
    <PageHeader kicker="Research / Market impact" title="Execution" description="A clear view of the assumptions sitting between a model signal and reported P&L, and — where returned — real cost-sensitivity evidence for the active experiment." />

    <Panel eyebrow="ACTIVE EXPERIMENT" title={active.experiment_id ?? "Unlogged run"} subtitle="Execution assumptions configured for this experiment." action={hasCostDetail ? <Badge tone="good">COST DATA AVAILABLE</Badge> : <Badge tone="warning">SUMMARY ONLY</Badge>}>
      <div className="card-grid-4">
        <Stat label="Spread (pips)" value={cfg?.spread_pips!=null?String(cfg.spread_pips):'—'} tone="accent" hint={TERM_DEFINITIONS.spread.short}/>
        <Stat label="Slippage (pips)" value={cfg?.slippage_pips!=null?String(cfg.slippage_pips):'—'} hint={TERM_DEFINITIONS.slippage.short}/>
        <Stat label="Latency (bars)" value={cfg?.latency_bars!=null?String(cfg.latency_bars):'1 (fixed — not exposed via API request)'} hint={TERM_DEFINITIONS.latency.short}/>
        <Stat label="Instrument" value={active.instrument}/>
      </div>
    </Panel>

    {!hasCostDetail && (
      <Panel title="Cost-sensitivity detail not available"><p style={{color:'var(--text-2)',fontSize:11,lineHeight:1.8}}>Cost-sensitivity curves (gross vs. net Sharpe at 0x/0.5x/1x/2x/4x the configured spread &amp; slippage) are only returned in the immediate response of <code className="mono">/api/research/run</code>, and are not persisted by the experiment registry. Re-run this configuration in Research Lab to see this analysis.</p></Panel>
    )}

    {hasCostDetail && (
      <Panel eyebrow="EVIDENCE" title="Cost sensitivity curve" subtitle="Averaged across folds — how Sharpe and cost drag change as spread/slippage are stressed relative to the configured assumptions.">
        <div className="table-wrap"><table className="data-table">
          <thead><tr><th>Cost multiplier</th><th>Avg gross Sharpe</th><th>Interpretation</th><th>Avg net Sharpe</th><th>Net interpretation</th><th>Avg total cost drag</th></tr></thead>
          <tbody>{multipliers.map(m => { const b = byMultiplier.get(m)!; const g = safeAvg(b.gross_sharpe), n = safeAvg(b.net_sharpe), d = safeAvg(b.total_cost_drag);
            return <tr key={m}>
              <td className="mono">{m}x{m===1?<Badge tone="accent">CONFIGURED</Badge>:null}</td>
              <td className="mono">{g!=null?g.toFixed(3):'—'}</td>
              <td><MetricBadge metric="sharpe" value={g}/></td>
              <td className="mono" style={{color:n!=null&&n>0?'var(--good)':n!=null&&n<0?'var(--bad)':'var(--text-2)'}}>{n!=null?n.toFixed(3):'—'}</td>
              <td><MetricBadge metric="sharpe" value={n}/></td>
              <td className="mono">{d!=null?d.toFixed(5):'—'}</td>
            </tr>;
          })}</tbody>
        </table></div>
        {(() => {
          const netSharpes = multipliers.map(m => safeAvg(byMultiplier.get(m)!.net_sharpe)).filter(v => v != null);
          const allIdentical = netSharpes.length > 1 && Math.abs(Math.max(...netSharpes) - Math.min(...netSharpes)) < 0.001;
          const allDragsZero = multipliers.every(m => {
            const d = safeAvg(byMultiplier.get(m)!.total_cost_drag);
            return d == null || Math.abs(d) < 1e-9;
          });
          if (allIdentical || allDragsZero) {
            return <div style={{marginTop:14,padding:'10px 12px',background:'var(--surface-2)',borderRadius:6,border:'1px solid var(--warn)'}}><div style={{display:'flex',alignItems:'center',gap:8}}><Badge tone="warning">COST INSENSITIVITY DETECTED</Badge><span style={{fontSize:10,color:'var(--text-2)'}}>Net Sharpe and cost drag are nearly identical across all multipliers. This typically indicates very low turnover (infrequent trading), meaning transaction costs have minimal impact on this strategy. Cost assumptions are being applied correctly but have little effect.</span></div></div>;
          }
          return null;
        })()}
        <p style={{fontSize:10,color:'var(--text-3)',lineHeight:1.7,marginTop:14}}>Fill-level detail (individual fill prices, discrete slippage per order) is not returned by the backend&apos;s execution model — it reports aggregated cost-drag and Sharpe impact only.</p>
        <MetricHeuristicsNote/>
      </Panel>
    )}

    <Panel eyebrow="EXECUTION MODEL" title="Signal → order → fill → P&L" subtitle="The existing research engine applies latency, spread and slippage before risk metrics are calculated.">
      <div className="pipeline"><div className="pipeline-step active"><b>Signal</b><small>Strategy decision</small></div><div className="pipeline-step"><b>Latency</b><small>Discrete bar delay</small></div><div className="pipeline-step"><b>Spread</b><small>Bid / ask cost</small></div><div className="pipeline-step"><b>Slippage</b><small>Adverse movement</small></div><div className="pipeline-step"><b>Net P&L</b><small>Reported result</small></div></div>
    </Panel>

    <Panel title="Native execution engine" subtitle="Compatibility note"><div className="split"><p style={{color:'var(--text-2)',fontSize:11,lineHeight:1.75,maxWidth:760}}>Higher-fidelity order-book and fill simulation is available through the existing native C++ engine, but is not wired into the research API&apos;s cost-sensitivity response used above. Standard research runs use the Python execution model shown here.</p><Badge tone="good">BACKEND UNCHANGED</Badge></div></Panel>

    <Panel eyebrow="NEXT STEP" title="Continue the research journey"><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Link href="/microstructure"><Button size="lg">Next → Microstructure</Button></Link></div></Panel>
  </div>;
}
