"use client";

import Link from "next/link";
import { Panel, PageHeader, Badge, Button, Stat, EmptyState } from "@/components/Panel";
import { ResearchJourney } from "@/components/ResearchJourney";
import { useActiveResearch, hasExperiment } from "@/lib/research-context";

export default function PaperTradingPage() {
  const active = useActiveResearch();

  return <div className="stack">
    <ResearchJourney current="paper"/>
    <PageHeader kicker="Simulation / Controlled environment" title="Paper Trading" description="A clearly separated research simulation surface — never presented as live brokerage activity." actions={<Link href="/research"><Button variant="secondary" size="sm">Research first →</Button></Link>} />

    {hasExperiment(active) ? (
      <Panel eyebrow="ACTIVE STRATEGY" title={active!.experiment_id ?? "Unlogged run"} subtitle="Inherited from your current research context." action={<Badge tone="warning">PAPER / SIMULATION ONLY</Badge>}>
        <div className="card-grid-4">
          <Stat label="Experiment ID" value={active!.experiment_id ?? '—'} tone="accent"/>
          <Stat label="Dataset" value={active!.dataset?.dataset_id==='demo' ? 'Demo (synthetic)' : (active!.dataset?.dataset_id?.slice(0,10) ?? '—')}/>
          <Stat label="Instrument" value={active!.instrument}/>
          <Stat label="Timeframe" value={active!.timeframe}/>
        </div>
      </Panel>
    ) : active?.dataset && active.dataset.dataset_id !== 'demo' ? (
      <Panel><EmptyState title={`${active.instrument} · ${active.timeframe} selected — no strategy yet`} description="Paper Trading inherits its strategy from a completed research experiment. Run Research on this dataset first." action={<Link href={`/research?dataset_id=${active.dataset.dataset_id}`}><Button>Run Research on this dataset →</Button></Link>} /></Panel>
    ) : (
      <Panel><EmptyState title="No active strategy" description="Run Research first — Paper Trading inherits its context from the active research experiment." action={<Link href="/research"><Button>Go to Research Lab →</Button></Link>} /></Panel>
    )}

    <Panel className="hero-panel" eyebrow="SIMULATION STATUS">
      <div className="split"><div><div style={{fontSize:26,letterSpacing:'-.04em',fontWeight:620}}>Paper trading engine not connected</div><p style={{color:'var(--text-3)',fontSize:10,marginTop:6}}>The backend exposes no paper-trading or live-order API (only /api/datasets, /api/research/run and /api/experiments). No simulated positions, fills or P&L are generated by this interface.</p></div><Badge tone="warning">NOT AVAILABLE</Badge></div>
    </Panel>

    <div className="card-grid-2">
      <Panel title="Research-to-paper flow" subtitle="The intended sequence keeps simulation grounded in research evidence."><div className="pipeline"><div className="pipeline-step"><b>01</b><small>Dataset</small></div><div className="pipeline-step"><b>02</b><small>Research</small></div><div className="pipeline-step active"><b>03</b><small>Validate</small></div><div className="pipeline-step"><b>04</b><small>Promote</small></div><div className="pipeline-step"><b>05</b><small>Simulate</small></div></div></Panel>
      <Panel title="What would be inherited if connected" subtitle="Not currently backed by a live engine — shown for context only"><div className="list-clean"><div className="list-row"><strong>Position limits</strong><Badge>WOULD INHERIT</Badge></div><div className="list-row"><strong>Regime filters</strong><Badge>WOULD INHERIT</Badge></div><div className="list-row"><strong>Spread / slippage</strong><Badge>WOULD INHERIT</Badge></div><div className="list-row"><strong>Latency</strong><Badge>WOULD INHERIT</Badge></div></div></Panel>
    </div>

    <Panel title="Current application boundary"><p style={{color:'var(--text-2)',fontSize:11,lineHeight:1.8}}>To add real paper trading, the backend would need a dedicated endpoint (e.g. an order-simulation service consuming the active experiment&apos;s signal + execution assumptions). Until that exists, this page intentionally shows its limitation rather than fabricating positions, fills or P&L.</p></Panel>

    <Panel eyebrow="NEXT STEP" title="Review the full research record"><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Link href="/experiments"><Button size="lg">Open Experiment Registry →</Button></Link></div></Panel>
  </div>;
}
